"""Add company_dev Association Table

Revision ID: 62648c726841
Revises: cae27465f34e
Create Date: 2023-08-10 13:05:28.546419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62648c726841'
down_revision = 'cae27465f34e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies_devs',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('dev_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_companies_devs_company_id_companies')),
    sa.ForeignKeyConstraint(['dev_id'], ['devs.id'], name=op.f('fk_companies_devs_dev_id_devs')),
    sa.PrimaryKeyConstraint('company_id', 'dev_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies_devs')
    # ### end Alembic commands ###
